### ISSUE TITLE
Can't go to page in in /pshop edit

### ISSUE THREAD

**Issue by mgmadnesstv** [Tabuu/PermissionShopZ#10]
When trying edit the Permission Shop you can't go onto page 2 while in editmode

**Comment by Tabuu** [comment]
Thank you for reporting this issue. The issue will be fixed in the next release.

**Comment by mgmadnesstv** [comment]
Also if possible do you have a current 1.17 beta build i can use? my server relies on this.

**Comment by Tabuu** [comment]
> Also if possible do you have a current 1.17 beta build i can use? my server relies on this.

The page has not been officially updated, but you can use the current newest version of PermissionShopZ (1.0.0) with the 1.17 version of TabuuCore. Then PermissionShopZ will work on 1.17.

**Comment by mgmadnesstv** [comment]
Yeah this works, might also want to look into permissions been deleted on some server restarts from the pshop!

**Comment by Tabuu** [comment]
This issue has been resolved since release 2.0.0.
