### ISSUE TITLE
LuckPerms group integration.

### ISSUE THREAD

**Issue by NicBOMB** [Tabuu/PermissionShopZ#2]
I saw the plugin and thought it looked really compact and simple for my small server. I am already running LuckPerms 5.1.32 and EssentialsX 2.17.2.77 and needed a plugin that would handle rankups for my players. I use over 50 LuckPerms groups with lots of permissions and prefixes and the small easy to use GUI would be great. I ran "/pshop add 'RankName' 0.01 group.rankname". I tried using the item in the shop gui, but no prefixes or command access was updated. I then checked the server and found the error.

Attempting to build non-permission node with PermissionNode.Builder. permission = 'group.rankname', correct builder type = me.lucko.luckperms.common.node.types.Inheritance$Builder

If you could add support for group management and rank requirements for further purchases that would be great.

**Comment by Tabuu** [comment]
This enhancement has been added in commit f6cbffa. The enhancement will be added in the next release.

Changes:
 - You can now use group/inheritance nodes the same way you can use permission nodes.
