### ISSUE TITLE
Null-pointer exception when opening GUI.

### ISSUE THREAD

**Issue by Davdinges** [Tabuu/PermissionShopZ#5]
Heya Tabuu, 
I am using the PermissionshopZ pugin on 1.16.1. At first I used it on Spigot, it worked perfectly aside from some general feedback. However, updating to spigot 1.16.1 build 12 broke the plugin, opening the shop only returns "/permissionshopz" in chat. Reloading the plugin works fine.
I pasted the null-pointer in pastenbin:  https://pastebin.com/5t36Zv2f
I am using:
PermissionShopZ 0.4.2
Tabuucore: 2020.6.0
PaperMC build 12.

**Comment by Tabuu** [comment]
This issue was fixed!
